### ISSUE TITLE
Items remaining to be incorporated into the next iteration of the roadmap

### ISSUE THREAD

**Issue by butlerpd** [SasView/documents#7]
- [ ] refactor handling  of multiple data sets for various use cases/workflows in conjunction with NXcanSAS
- [ ] Add support for handling multiple scattering
- [ ] Extend available integration options such as adaptive, MC integration etc
- [ ] Implement custom workflows (such as: finding the contrast match point from a series of datasets; pulling out the nuclear vs magnetic scattering from several polarised 2D datasets or from 1D cuts parallel and perpendicular to the field, etc.)
- [ ] P/*S computation enhancements (adding locally monodisperse approx.; fix volume fraction issue, etc.)
- [ ] reimplement the orientation viewer to 5.x (a 5.1 task for feature parity)
- [ ] simplify dependency/requirements issues (minimalize number/ well supported/ single source for all requirements (for all platforms and release vs development etc) 

### Need to edit the relevant lines in the roadmap to make clear they cove these as well
- [ ] Implement calculation of 2D scattering patterns from oriented systems (https://doi.org/10.1107/S1600576717005179)
  * This looks like it would be another builder/engine for the general scattering calculator like sponge and mcsim and the current oriented engine (which may be wrong). If so this should be part of that bullet in the roadmap rather than a separate bullet.
- [ ] Clean up resolution calculations (ensure each q has a basis of support in calculated q values, then submit that full vector to the calculator as one piece; the current method computes the end pieces separately from the middle)
  * while no doubt useful, as stated it seems much too granular for the roadmap?
  * @smk78 says: this could be part of a larger resolution task with implementing user-defined resolution functions? Also need to fix the problem with smearing not being saved/loaded in projects!

### Questions
* Is starting to implement PRISM really a task for 5.1, or later?
  * @butlerpd says: only because in talking to Tyler he says it (it = pyprism) is technically ready now to integrate (he thinks) and he is considering coming to the October code camp. Otherwise no, it would not make sense.

**Comment by butlerpd** [comment]
OWNERSHIP of Talking Stick
- [ ] Wojciech
- [ ] Steve
- [ ] Paul
